import Head from "next/head";
import { makeStyles } from "@material-ui/core/styles";
import Card from "@material-ui/core/Card";
import CardActions from "@material-ui/core/CardActions";
import CardContent from "@material-ui/core/CardContent";
import Button from "@material-ui/core/Button";
import Typography from "@material-ui/core/Typography";
import Container from "@material-ui/core/Container";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useRouter } from "next/router";

const useStyles = makeStyles({
  root: {
    minWidth: 275,
  },
  bullet: {
    display: "inline-block",
    margin: "0 2px",
    transform: "scale(0.8)",
  },
  title: {
    fontSize: 14,
  },
  pos: {
    marginBottom: 12,
  },
});

function setCookie(cname, cvalue, exdays) {
  const d = new Date();
  d.setTime(d.getTime() + exdays * 24 * 60 * 60 * 1000);
  let expires = "expires=" + d.toUTCString();
  document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
}

export default function Home() {
  const router = useRouter();
  const classes = useStyles();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Sign in as :</h1>

        <div className={styles.grid}>
          <div
            className={styles.card}
            onClick={() => {
              sessionStorage.setItem("doctor", false);
              setCookie("doctor", false, 1000);
              router.push("/api/auth/signin");
            }}
          >
            <h2>Patient &rarr;</h2>
            <p>Sign in as a patient to upload and manage medical records.</p>
          </div>

          <div
            onClick={() => {
              sessionStorage.setItem("doctor", true);
              setCookie("doctor", true, 1000);
              router.push("/api/auth/signin");
            }}
            className={styles.card}
          >
            <h2>Doctor &rarr;</h2>
            <p>Sign in as a doctor to view the patients medical records.</p>
          </div>
        </div>
      </main>
    </div>
  );
}
